# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38cc78f1845ef72f38b768534b0e25265248e034cfbab787ad24e0d6b58d55b92d56e78dbc09283ad33ee5577338bbcb19f8d9eb6f45dab4539e7bb20553679b

test:
  secret_key_base: 9227e6910717088bfdc306f99abad88a5890fffdfa2dcc325a641bb32b407cab7a3010a7c5a3aba14fe6914669570979abecb5a7ee84833ffa11033703f5a1e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
